environment: dev # dev|prod|test

db:
  host: biblys-mysql
#  host_for_cli: 127.0.0.1
  port: 3306
  user: root
  pass:
  base: biblys

site: 1

#logs:
#  sql: false
#  errors: false
#  deprecations: false
#
#maintenance:
#  enabled: true
#  title: Une opération de maintenance est en cours.
#  message: Merci de réessayer d'ici quelques instants.
#  link: https://status.biblys.fr

#cloud:
#  cdn: false
#  public_key: cus_abcd1234
#  secret_key: abcd1234
#  domains: paronymie.fr
#  base_url: https://biblys.fr
#  hot_news:
#    message: Hello world!
#    link: https://www.biblys.fr/

#authentication:
#  secret: abcdefghijklmnopqrstuvxyz12345678

#axys:
#  client_id: abcd1234
#  client_secret: efgh5678
#  redirect_uri: http://paronymie.fr/openid/callback
#  base_uri: https://axys.me/

smtp:
  host: biblys-mailpit
  user: sender@example.com
  pass: password123
  port: 1025
## Force HTTPS
#https: true

## Set HTTP Strict Transport Security to 6 months
#hsts: true

cache:
  driver: filesystem # filesystem|apc
  ttl: 86400

#images:
#  path: public/images/
#  base_url: /images/
#  cdn:
#    service: weserv

## Path to composer home folder must be defined
## to allow auto-updates
#composer_home: /Users/biblys/.composer

## Cron key to allow external web cron service
#cron:
#  key: abcd1234

#media_path: /public/media
#media_url: /media
#downloadable_path: ../dlfiles/

#paypal:
#  client_id: paypal_id
#  client_secret: paypal_secret_key
#  environment: production

#payplug:
#  secret: sk_test_abcd1234

#stripe:
#  public_key: pk_test_abcd1234
#  secret_key: sk_test_abcd1234
#  endpoint_secret: whsec_abcd1234

#recaptcha:
#  sitekey: recaptcha_sitekey
#  secret: recaptcha_secret

#images_cdn:
#  service: cloudimage|weserv
#  options:
#    token: abcdef12345 # cloudimage only

## Place des libraires stock export
#placedeslibraires:
#  shop_id: 12345
#  login: SHOP-PDL
#  password: 1234-Pdl

## Matomo Analytics tracker
## https://matomo.org
#  domain: biblys.matomo.cloud
#  site_id: 1
#  login: biblys
#  md5pass: abcd1234efgh5678

## Umami Analytics Tracker
## https://cloud.umami.is/
#umami:
#  website_id: abcd-1234-efgh-5678
#  share_url: https://analytics.umami.is/share/9876ijkl5432mnop/biblys.fr

## Sentry
## https://sentry.io
#sentry:
#  dsn: https://abcd1234@efgh5678.ingest.de.sentry.io/ijlk9876

## Rollbar
#rollbar:
#  access_token: abcdef12345
#  environment: biblys-local

## Gleeph
#gleeph:
#  api_key: abcdef12345
#  environment: prod

## Mailjet
#mailing:
#  service: mailjet|brevo
#  api_key: ghijkl789012
#  list_id: 321654987

## LemonInk Watermarking
## https://lemonink.co
#lemonink:
#  api_key: mnopqrst345678

## Mondial Relay Shipping
## https://connect.mondialrelay.com/
#mondial_relay:
#  code_enseigne: ABCD1234
#  private_key: abcdefghij
#  id_relais_collecte: 123456